# Train command: python train.py --data coco128.yaml
# Default dataset location is next to /yolov5:
#   /parent_folder
#     /coco128
#     /yolov5


#download command/URL (optional)
#download: https://github.com/ultralytics/yolov5/releases/download/v1.0/coco128.zip

# train and val data as 1) directory: path/images/, 2) file: path/images.txt, or 3) list: [path1/images/, path2/images/]
train: /content/drive/MyDrive/yolov5/traindata/imgs #images path in colab
val: /content/drive/MyDrive/yolov5/traindata/imgs  #images path in colab

# number of classes
nc: 5

# class names
names: [ 'Mask', 'Face_Shield', 'Goggles', 'Gloves', 'Coverall']  #labels
